# Generated by Django 4.1.6 on 2023-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_giftcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards/%d'),
        ),
    ]
