# Generated by Django 4.1.6 on 2023-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_giftcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='type',
            field=models.CharField(blank=True, default='phone', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
    ]
