# Generated by Django 4.1.6 on 2023-07-18 08:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_login_user_coinhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserve_phone_number',
            field=models.CharField(default='', max_length=30, validators=[users.models.validate_phone_number]),
            preserve_default=False,
        ),
    ]
