# Generated by Django 4.1.6 on 2023-07-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0007_application_post_logout_redirect_uris'),
        ('users', '0010_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Application',
        ),
    ]
