# Generated by Django 4.1.6 on 2023-07-23 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_application_alter_user_two_factor_auth_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
