# Generated by Django 4.1.6 on 2023-07-27 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_language_user_region_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservePhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, validators=[users.models.validators.validate_phone_number])),
                ('verification_code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reserve_phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='tm', max_length=10),
        ),
        migrations.AddField(
            model_name='reservephonenumber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_phone_number', to=settings.AUTH_USER_MODEL),
        ),
    ]
